- name: deploy s-pdf container
  community.docker.docker_container:
    name: some-s-pdf-container
    image: "frooodle/s-pdf:latest"
    state: started
    restart: true
    restart_policy: always
    networks:
      - name: proxy_network
    labels:
      caddy: "spdf.{{ vault_internal_domain_name }}"
      caddy.reverse_proxy: "{{ '{{' }}upstreams 8080{{ '}}' }}"
