
- name: Install apcupsd
  apt:
    pkg: apcupsd
    state: installed

- name: Install boto3 to root env
  become: yes
  shell: "/opt/anaconda/bin/conda install -y boto3"

- name: Copy over configuration files
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apcupsd/{{ item }}"
  with_items:
    - apcupsd.conf
    - offbattery
    - onbattery
    - doshutdown

- include_role:
    name: copy-scripts
  vars:
    script_to_copy: send_sns_alert.py

# name: Create directory for scripts
# become: yes
# file:
#   state: directory
#   path: /opt/user-scripts

# name: copy alert script to directory
# become: yes
# template:
#   src: "{{ item }}"
#   dest: /opt/user-scripts
# loop:
#   - send_sns_alert.py

