
- name: Install apcupsd
  apt:
    name: apcupsd
    state: present

- name: Copy over configuration files
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apcupsd/{{ item }}"
  with_items:
    - apcupsd.conf
    - offbattery
    - onbattery
    - doshutdown
