---
- name: install apache2 and phpmyadmin
  apt: pkg={{item}} state=installed update_cache=true install_recommends=no
  become: true
  with_items:
    - phpmyadmin
    - apache2

- name: copy apache2 configuration
  copy:
      src: "phpmyadmin/{{ item }}"
      dest: /etc/phpmyadmin
      owner: root
      group: root
      mode: 0644
  with_items:
      - apache.conf

- name: Add in phpmyadmin configuration
  template:
      src: "{{ item }}.j2"
      dest: "/etc/phpmyadmin/{{ item }}"
      owner: root
      group: root
      mode: 0644
  with_items:
      - config.inc.php
      - config-db.php

- name: Create apache2 conf.d directory
  file:
      path: /etc/apache2/conf.d
      state: directory
      mode: 0755
      owner: root
      group: root

- name: symlink phpmyadmin config to apache2
  file:
      src: /etc/phpmyadmin/apache.conf
      dest: /etc/apache2/conf.d/phpmyadmin.conf
      state: link

- name: Update apache2 to include conf.d
  lineinfile:
      dest: /etc/apache2/apache2.conf
      state: present
      line: "Include conf.d/"
      insertafter: EOF
  notify: 
    - Restart apache2

