#!/usr/bin/bash -e

export AWS_ACCESS_KEY_ID={{ vault_aws_keys['db-backup'].key_id }}
export AWS_SECRET_ACCESS_KEY={{ vault_aws_keys['db-backup'].access_key }}
export AWS_DEFAULT_REGION={{ vault_aws_default_region }}

backup_filename=homebox_data.tgz

tar czf "/tmp/${backup_filename}" -C {{ docker_data_path }}/homebox/ .

/usr/local/bin/aws s3 cp --quiet "/tmp/${backup_filename}" "s3://{{ vault_aws_projects_bucket }}/backups/homebox/${backup_filename}"

rm "/tmp/${backup_filename}"
