---
- name: install vim
  apt: pkg={{item}}  state=installed update_cache=true
  become: true
  with_items:
    - vim
    - git
    - stow
  when: ansible_distribution == "Debian" # freepbx is centos

- name: install vim Yum
  yum: pkg={{item}}  state=installed update_cache=true
  become: true
  with_items:
    - vim
    - git
    - stow
  when: ansible_distribution != "Debian" # freepbx is centos


# Configure vim with plugins and dotfiles
- name: checkout dotfiles
  become: yes
  become_user: "{{ user_to_configure }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ user_home_directory }}/dotfiles"

- name: checkout vundle
  become: yes
  become_user: "{{ user_to_configure }}"
  git:
    repo: "{{ vundle_repo }}"
    dest: '{{ user_home_directory  }}/.vim/bundle/Vundle.vim'

- name: stow vimrc file
  become: yes
  become_user: "{{ user_to_configure }}"
  shell: stow -d '{{ user_home_directory }}/dotfiles' -t '{{ user_home_directory }}' '{{ item }}'
  with_items:
    - vim

- name: install vim plugins
  become: yes
  become_user: "{{ user_to_configure }}"
  shell: vim -E -s -c "source ~/.vimrc" +PluginInstall +qall
  ignore_errors: true
