- name: make data dir
  ansible.builtin.file:
    path: "{{ docker_data_path }}/homebox"
    recurse: true
    state: directory
    owner: root
    group: root

- name: deploy homebox container
  community.docker.docker_container:
    name: some-homebox-container
    image: "ghcr.io/sysadminsmedia/homebox:latest"
    state: started
    restart: true
    restart_policy: always
    env:
      HBOX_DATABASE_DRIVER: postgres
      HBOX_DATABASE_SSL_MODE: disable
      HBOX_DATABASE_HOST: some-postgres-container
      HBOX_DATABASE_PORT: "5432"
      HBOX_DATABASE_DATABASE: homebox
      HBOX_DATABASE_USERNAME: homebox
      HBOX_DATABASE_PASSWORD: "{{ vault_postgres_homebox_password }}"
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: "10"
      # Use a strong random string for the pepper in production, it will be used to hash API keys and make them more secure
      HBOX_AUTH_API_KEY_PEPPER: "{{ vault_homebox_api_key_pepper }}"
    volumes:
      - "{{ docker_data_path }}/homebox:/data"
    networks:
      - name: db_network
      - name: proxy_network
    labels:
      caddy: "homebox.{{ vault_internal_domain_name }}"
      caddy.reverse_proxy: "{{ '{{' }}upstreams 7745{{ '}}' }}"

- name: Setup awscli
  ansible.builtin.include_role:
    name: setup_awscli

- name: copy over backup script
  ansible.builtin.include_role:
    name: copy_scripts
    apply:
      become: true
  vars:
    script_to_copy: backup_homebox_data

- name: set permissions for backup
  become: true
  ansible.builtin.file:
    path: "{{ scripts_dir }}/backup_homebox_data"
    owner: root
    group: root
    mode: "0700"

- name: add backup job for db
  become: true
  ansible.builtin.cron:
    name: "backup bookstack db"
    special_time: weekly
    job: "{{ scripts_dir }}/backup_homebox_data"
