- name: make data dir
  ansible.builtin.file:
    path: "{{ docker_data_path }}/lubelogger"
    recurse: true
    state: directory
    owner: root
    group: root

- name: deploy lubelogger container
  community.docker.docker_container:
    name: some-lubelogger-container
    image: "ghcr.io/hargata/lubelogger:v1.6.4"
    volumes:
      - "{{ docker_data_path }}/lubelogger/config:/App/config"
      - "{{ docker_data_path }}/lubelogger/data:/App/data"
      - "{{ docker_data_path }}/lubelogger/documents:/App/wwwroot/documents"
      - "{{ docker_data_path }}/lubelogger/images:/App/wwwroot/images"
      - "{{ docker_data_path }}/lubelogger/temp:/App/wwwroot/temp"
      - "{{ docker_data_path }}/lubelogger/log:/App/log"
      - "{{ docker_data_path }}/lubelogger/keys:/root/.aspnet/DataProtection-Keys"
    state: started
    restart: true
    restart_policy: always
    labels:
      caddy: "lubelogger.{{ vault_internal_domain_name }}"
      caddy.reverse_proxy: "{{ '{{' }}upstreams 8080{{ '}}' }}"
    env:
      POSTGRES_CONNECTION: "Host=some-postgres-container:5432;Username=postgres;Password={{ vault_postgres_root_password }};Database=lubelogger;"
    networks:
      - name: proxy_network
      - name: db_network
