repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v26.2.0
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        description: Run configurations on .ansible-lint file
        entry: python3 -m ansiblelint -v --force-color
        language_version: python3.12
        pass_filenames: false
        always_run: true
