---
- name: Configure APT Server
  hosts: apt-server
  remote_user: deploy
  become: true

  roles:
# - { role: add_and_setup_deploy_user}
# - { role: base_setup}
# - { role: install-and-configure-letsencrypt }
# - { role: setup-smartmontools }
# - { role: install-rsnapshot }
# - { role: install-rclone }
# - { role: install-docker-base }
# - { role: deploy_docker_container }
# - { role: install-samba, become: yes }
# - { role: deploy-docker-redis }
# - { role: deploy_docker_apache }
# - { role: deploy-docker-mysql-phpmyadmin }
# - { role: deploy-docker-postgres-adminer }
# - { role: deploy-docker-immich }
# - { role: deploy-docker-nexus }
# - { role: deploy-docker-paperless-ngx }
# - { role: deploy-docker-emby }
  - { role: deploy-docker-homer }
# - { role: deploy-docker-s-pdf }
# - { role: deploy-docker-lubelogger }
    # needs tags=all,apt-server to add proper monitoring
# - { role: setup-nagios-monitoring, become: true }
