---
- hosts: garage-door
  remote_user: deploy
  become: true
  roles:
    - { role: base-setup, become: yes }
    - { role: install-temperature-sensors-service }
    - { role: install-garage-door-service }
    - { role: install-aws-temp-scripts, become: true }
