---
- hosts: garage-door
  remote_user: deploy
  become: true
  roles:
    - { role: common, tags: ['base'] }
    - { role: install-raspberry-pi-microservice, microservice_name: temperature_sensors, microservice_port: 25002, tags: ['services']}
    - { role: install-garage-door-service, microservice_name: garage_door, microservice_port: 25678, tags: ['garage-door', 'services']}
