---
- hosts: garage-door
# remote_user: deploy
  become: true
  roles:
#   - { role: common, tags: ['base'] }
    - { role: install-temperature-sensors-service }
    - { role: install-garage-door-service }
    - { role: install-aws-temp-scripts, garage_door_user: garage-door, become: true }
