
---
- hosts: main-server
# remote_user: deploy
  roles:
    - { role: base-setup, become: yes }
    - { role: add-and-setup-deploy-user, become: yes }
    - { role: install-and-configure-vim-for-user, user_to_configure: deploy }
    - { role: install-and-configure-ssmtp, tags: ['ssmtp'] }
    - { role: install-and-configure-letsencrypt }
    - { role: setup-apcupsd, tags: ['apcupsd']}
    - { role: install-rsnapshot, become: yes }
    - { role: install-samba, become: yes }

    - { role: deploy-docker-container }

