
---
- hosts: main-server
  remote_user: deploy
  become: yes
  roles:
  - { role: setup-main-server }
  - { role: base-setup}
  - { role: add-and-setup-deploy-user}
  - { role: install-and-configure-ssmtp, tags: ['ssmtp'] }
  - { role: install-and-configure-letsencrypt }
  - { role: setup-apcupsd, tags: ['apcupsd']}
  - { role: install-rsnapshot }
  - { role: install-samba }
  - { role: setup-aws-traffic-shaping, interface_name: enp4s0 }

  - { role: deploy-docker-container }
  # needs tags=all,main-server to add proper monitoring
  - { role: setup-nagios-monitoring }

