---
- name: Configure Main Server
  hosts: main-server
  remote_user: deploy
  become: true

  roles:
    - { role: setup-main-server }
    - { role: add_and_setup_deploy_user }
    - { role: base_setup }
    - { role: install_and_configure_ssmtp, tags: ['ssmtp'] }
    - { role: install_and_configure_letsencrypt }
    - { role: setup-apcupsd, tags: ['apcupsd'] }
    - { role: install-rsnapshot }
    - { role: setup-smartmontools }
    - { role: install-samba }
    - { role: install-rclone }
    - { role: install-docker-base }
    - { role: deploy_docker_apache }
    - { role: deploy_wireguard }
    # needs tags=all,main-server to add proper monitoring
    - { role: setup-nagios-monitoring }

