
---
- hosts: main-server
  remote_user: deploy
  become: yes
  roles:
    - { role: base-setup}
    - { role: add-and-setup-deploy-user}
    - { role: install-and-configure-ssmtp, tags: ['ssmtp'] }
    - { role: install-and-configure-letsencrypt }
    - { role: setup-apcupsd, tags: ['apcupsd']}
    - { role: install-rsnapshot }
    - { role: install-samba }

    - { role: deploy-docker-container }

