---
- name: Configure Main Server
  hosts: main-server
  remote_user: deploy
  become: true

  roles:
    - { role: setup_main_server }
    - { role: add_and_setup_deploy_user }
    - { role: base_setup }
    - { role: install_and_configure_ssmtp, tags: ['ssmtp'] }
    - { role: install_and_configure_letsencrypt }
    - { role: setup_apcupsd, tags: ['apcupsd'] }
    - { role: install_rsnapshot }
    - { role: setup_smartmontools }
    - { role: install_samba }
    - { role: install_rclone }
    - { role: install_docker_base }
    - { role: deploy_docker_apache }
    - { role: deploy_wireguard }
    # needs tags=all,main-server to add proper monitoring
    - { role: setup_nagios_monitoring }

