
- name: Configure Nagios Server
  hosts: nagios-server
  remote_user: deploy

  roles:
#     - { role: add-and-setup-deploy-user, become: true }
#     - { role: base-setup, become: true }
    - { role: install-nagios-server, become: true }
    # needs tags=all,nagios-server to add proper monitoring
#     - { role: setup-nagios-monitoring, become: true }
