
---
- hosts: pi-hole
  remote_user: deploy
  become: yes
  roles:
# - { role: add_and_setup_deploy_user}
# - { role: base_setup}
# - { role: deploy_wireguard }
  # needs tags=all to add proper monitoring
  - { role: setup-nagios-monitoring, become: yes }
  tasks:
    - name: Add weekly update run for pi-hole
      cron:
        name: "Update pi-hole every Wed at 3:23 AM"
        minute: "23"
        hour: "3"
        day: "3"
        job: "/usr/local/bin/pihole -up > /dev/null"

    - name: Add monthly update lists for pi-hole
      cron:
        name: "Update pi-hole lists monthly"
        special_time: "monthly"
        job: "/usr/local/bin/pihole -g > /dev/null"
