
---
- hosts: pi-hole
  remote_user: deploy
  become: yes
  roles:
# - { role: add-and-setup-deploy-user}
# - { role: base-setup}
# - { role: deploy-wireguard }
  # needs tags=all to add proper monitoring
  - { role: setup-nagios-monitoring, become: yes }

