
- name: Configure Proxmox
  hosts: proxmox
  remote_user: deploy

  roles:
    - { role: install_apprise, become: true }
#     - { role: base_setup, become: true }
#     - { role: add_and_setup_deploy_user, become: true }
    - { role: setup-apcupsd, become: true }
    # needs tags=all,proxmox to add proper monitoring
#     - { role: setup-nagios-monitoring, become: true }
