- name: download check_docker plugin
  get_url:
    url: "https://raw.githubusercontent.com/timdaman/check_docker/master/check_docker/check_docker.py"
    dest: /usr/lib/nagios/plugins/check_docker
    owner: root
    group: root
    mode: "0755"

- name: Add checks for disk space
  cron:
    name: "Nagios: {{ item.key }}"
    minute: "{{ check_interval_mins }}"
    job: "{{ nagios_cron_randomizer }} && SERVICE_NAME=\"Disk {{ item.key }}\" CHECK_CMD=check_disk CHECK_ARGS=\"{{ item.value }}\" {{ scripts_dir }}/submit_nagios_check.sh > /dev/null"
  loop: "{{ disks | dict2items }}"
  vars:
    disks:
      mnt-nas_disk: "/mnt/nas-disk"
      mnt-vm_drives: "/mnt/vm-drives"
      mnt-nas_backup: "/mnt/nas_backup"

- name: Add checks for containers
  cron:
    name: "Nagios: {{ item }}"
    minute: "{{ check_interval_mins }}"
    job: "{{ nagios_cron_randomizer }} && SERVICE_NAME=\"Docker {{ item }}\" CHECK_CMD=check_docker CHECK_ARGS=\"--status=running --containers {{ item }} --present\" {{ scripts_dir }}/submit_nagios_check.sh > /dev/null"
  loop:
    - some-apache2-container
    - some-homer-container
    - some-phpmyadmin-container
    - some-redis-container
    - some-mariadb-container
    - some-nexus-container
    - some-immich-container
    - some-emby-container
