- name: install nagios nrpe plugins
  apt: 
    name: ['nagios-plugins', 'nagios-plugins-contrib']
    state: present

# need to set permissions here so role is not used
- name: copy over nrdp client scripts
  copy:
    src: send_nrdp.sh
    dest: "{{ scripts_dir }}/"
    owner: root
    group: root
    mode: '0744'

- name: copy over nrdp client scripts
  template:
    src: submit_nagios_check.sh
    dest: "{{ scripts_dir }}/"
    owner: root
    group: root
    mode: '0744'

- include_tasks:
    file: basic.yaml

- include_tasks:
    file: garage.yaml
    apply:
      tags:
        - garage
        - never

- include_tasks:
    file: main-server.yaml
    apply:
      tags:
        - main-server
        - never

- include_tasks:
    file: nagios-server.yaml
    apply:
      tags:
        - nagios-server
        - never
