- name: install nagios nrpe plugins
  apt: 
    name: nagios-plugins
    state: present

# need to set permissions here so role is not used
- name: copy over nrdp client scripts
  copy:
    src: send_nrdp.sh
    dest: "{{ scripts_dir }}"
    owner: root
    group: root
    mode: '0744'

- name: copy over nrdp client scripts
  template:
    src: submit_nagios_check.sh
    dest: "{{ scripts_dir }}"
    owner: root
    group: root
    mode: '0744'



# name: Edit config to allow NRPE server to connect to this host
# lineinfile:
#   dest: "/etc/nagios/nrpe.cfg"
#   state: present
#   regexp: "^allowed_hosts"
#   line: "allowed_hosts={{ groups['nagios-server'][0] }}"

# name: Restart nrpe
# service:
#   name: nagios-nrpe-server
#   state: restarted

# name: Set shell for nagios user
# user:
#   name: nagios
#   state: present
#   shell: /bin/sh

# name: Allow nagios-server to ssh into host without password
# authorized_key:
#   user: nagios
#   state: present
#   key: "{{ lookup('file', playbook_dir +'/nagios_pub_key.pub') }}"

