# noqa: yaml[empty-lines]
- name: Install smartmontools
  ansible.builtin.apt:
    name: smartmontools
    state: present

- name: Check if awscli exists
  ansible.builtin.stat:
    path: /usr/local/bin/aws
  register: awscli_result

- name: download and decompress awscli
  ansible.builtin.unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/"
    remote_src: true
    owner: root
    group: root
  when: not awscli_result.stat.exists

- name: run awscli installer
  ansible.builtin.shell:
    cmd: "/tmp/aws/install"
  when: not awscli_result.stat.exists

- name: copy over telegram alert script
  ansible.builtin.template:
    src: 10sendsnsalert
    dest: /etc/smartmontools/run.d
    owner: root
    group: root
    mode: "0744"

- name: copy over smartd config
  ansible.builtin.template:
    src: smartd.conf.j2
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: "0744"

- name: Enable service to run on boot and start
  become: true
  ansible.builtin.service:
    name: "smartmontools"
    state: restarted
    enabled: true

