- name: make data dir
  file:
    path: "{{ docker_nexus_data_path }}"
    recurse: yes
    state: directory
    owner: root
    group: root

- name: deploy nexus container
  docker_container:
    name: some-nexus-container
    image: "sonatype/nexus3:3.69.0"
    volumes:
      - "{{ docker_nexus_data_path }}:/nexus-data"
    state: started
    restart: yes
    restart_policy: always
    networks:
      - name: proxy_network
    ports:
      - 8081:8081
