---
- name: install useful packages
  apt: 
    pkg: "{{ item }}"
    state: installed
  with_items:
    - git
    - ntp
  when: ansible_distribution == "Debian" # freepbx is centos

- name: Set machine time to EST
  file:
    src: /usr/share/zoneinfo/America/New_York
    dest: /etc/localtime
    state: link
    owner: root
    group: root
