---
- name: install useful packages
  apt: 
    pkg: "{{ item }}"
    state: installed
  with_items:
    - git
    - ntp
    - curl
  when: ansible_distribution == "Debian" # freepbx is centos

- name: Set machine time to EST
  register: tz
  timezone:
    name: America/New_York

- name: Restart cron
  service:
    name: cron
    state: restarted
  when: tz.changed
