---
- name: install prereqs
  apt: pkg={{item}}  state=installed update_cache=true
  become: true
  with_items:
    - git
    - stow
  when: ansible_distribution == "Debian" # freepbx is centos

# Configure vim with plugins and dotfiles
- name: checkout dotfiles
  become: yes
  become_user: "{{ user_to_configure }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ user_home_directory }}/dotfiles"

- name: Remove old config files
  become: yes
  become_user: "{{ user_to_configure }}"
  file:
    path: "{{ user_home_directory }}/{{ item }}"
    state: absent
  with_items:
    - .bashrc
    - .bash_aliases
    - .screenrc
    - .gitconfig

- name: stow config files
  become: yes
  become_user: "{{ user_to_configure }}"
  shell: stow -d '{{ user_home_directory }}/dotfiles' -t '{{ user_home_directory }}' '{{ item }}'
  with_items:
    - bash
    - git
    - screen
