# cloud-config
apt:
  primary:
    - arches: [default]
      uri: "http://nexus.home.local/repository/ubuntu-archive"
bootcmd:
  - [mkdir, "-p", "/etc/systemd/resolved.conf.d/"]
  - printf "[Resolve]\nDNS=192.168.0.193 192.168.0.120\nDomains=~.\n" > /etc/systemd/resolved.conf.d/dns_servers.conf
  - [systemctl, restart, systemd-resolved]

packages:
  - git
  - screen
  - vim
  - stow

ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjwJ5uOpghZ4wafdnfgMm+EnQn22xlK1FbOdTM8H71RyCJz0/cJ5rk16tBkYtTn4oNj2lRbDvhRzXniR4JQKsdqxhKCqM9jRvenccc10AUyKZVY0hAx16EW7fWYhyh57NK5NvDWejj8nJYsNTacVm4ZJ/i8PYKuLm+sjHdFoEgy8tNFifwhBR3TxljtkHjNVPGEmN/pxCFAJxTWark5hqA5ry2PTpK15bp6FrzhRW0yNbWAYHPrcSTsdGZsHBL8ENg/eEqfignBvOpzgdJ5fWyr8W4XHE75TXBOSjtAHoSVeoOn22FDPBMBomUIQBYX92F+kQzjD9p5hkKaBdQF33lLLON28nl2e2hhbTgwDtnn+JejHxCES/lrQleafJiEl83WqYg0tj0OKQ31+nX1AKSYqPOE4gEqn2PNAH3Y7qX8Ptyp+gKFLQd5QR6iskIkCATP3Uq5OidnbNmvgthQzDfRn9oGC3P+xyHDS5XB6eV/Bza6r2lGn7Wm+Cq1MQw7Z0="

