# cloud-config
apt:
  primary:
    - arches: [default]
      uri: "http://nexus.home.local/repository/ubuntu-archive"
bootcmd:
  - [mkdir, "-p", "/etc/systemd/resolved.conf.d/"]
  - printf "[Resolve]\nDNS=192.168.0.193 192.168.0.120\nDomains=~.\n" > /etc/systemd/resolved.conf.d/dns_servers.conf
  - [systemctl, restart, systemd-resolved]

packages:
  - git
  - screen
  - vim
  - stow

