- name: "Generate ssh key for {{ user_to_configure }}"
  user:
    name: "{{ user_to_configure }}"
    generate_ssh_key: yes
    ssh_key_comment: "{{ user_to_configure}}@{{ ansible_hostname }}"

- name: Register user pub key
  shell: "cat {{ user_home_directory }}/.ssh/id_rsa.pub"
  register: ssh_pub_key

- name: Add deploy key
  github_deploy_key:
    owner: "avinash-oza"
    name: "{{ user_to_configure }} @ {{ ansible_hostname }}"
    repo: "home-projects"
    key:  "{{ ssh_pub_key.stdout }}"
    token: "{{ github_api_key }}"
# name: Add key to github
# github_key:
#   name: "{{ user_to_configure }} @ {{ ansible_hostname }}"
#   token: "{{ github_api_key }}"
#   pubkey: "{{ ssh_pub_key.stdout }}"

- name: Clone home-projects repo
  git:
    repo: "{{ home_projects_repo }}"
    dest: "{{ user_home_directory}}/home-projects"
    force: yes
    accept_hostkey: yes
    key_file: "{{ user_home_directory }}/.ssh/id_rsa"

- name: Convert ownership of repo to user
  file:
    path: "{{ user_home_directory }}/home-projects"
    owner: "{{ user_to_configure }}"
    group: "{{ user_to_configure }}"
    state: directory
    recurse: yes


