- name: Register user pub key
  shell: cat /home/{{ user_to_configure}}/.ssh/id_rsa.pub
  register: ssh_pub_key

- name: Add deploy key
  github_deploy_key:
    owner: "avinash-oza"
    name: "{{ user_to_configure }} @ {{ ansible_hostname }}"
    repo: "home-projects"
    key:  "{{ ssh_pub_key.stdout }}"
    token: XXX
# name: Add key to github
# github_key:
#   name: "{{ user_to_configure }} @ {{ ansible_hostname }}"
#   token: "{{ github_api_key }}"
#   pubkey: "{{ ssh_pub_key.stdout }}"

- name: Clone home-projects repo
  git:
    repo: "{{ home_projects_repo }}"
    dest: "/home/{{ user_to_configure }}/home-projects"
    accept_hostkey: yes
    key_file: "/home/{{ user_to_configure }}/.ssh/id_rsa"

- name: Convert ownership of repo to user
  file:
    path: "/home/{{ user_to_configure }}/home-projects"
    owner: "{{ user_to_configure }}"
    group: "{{ user_to_configure }}"
    state: directory
    recurse: yes


