- name: make data dir
  ansible.builtin.file:
    path: "{{ docker_data_path }}/emby"
    recurse: true
    state: directory
    owner: root
    group: root

- name: deploy emby container
  community.docker.docker_container:
    name: some-emby-container
    image: "emby/embyserver:4.10.0.14"
    state: started
    restart: true
    restart_policy: always
    volumes: "{{ vault_emby_mount_points }}"
    labels:
      caddy: "emby.{{ vault_internal_domain_name }}"
      caddy.reverse_proxy: "{{ '{{' }}upstreams 8096{{ '}}' }}"
    networks:
      - name: proxy_network
    devices:
      - /dev/dri:/dev/dri
    env:
      GIDLIST: "100,44"
