---
- name: create proxy network
  docker_network:
    name: proxy_network

- name: create db network
  docker_network:
    name: db_network

- name: create cache network
  docker_network:
    name: cache_network
