- include_tasks: docker-base.yaml
- include_tasks: docker-networks.yaml
- include_tasks: redis.yaml
- include_tasks: mysql-phpmyadmin.yaml
- include_tasks: apache2.yaml
- include_tasks: nextcloud.yaml
# unused for now
# include_tasks: mediawiki.yaml
- include_tasks: bookstack.yaml
- include_tasks: homer.yaml
- include_tasks: unifi.yaml
