---

- name: deploy mariadb container
  docker_container:
    name: some-mariadb-container
    image: "mariadb:10.5"
    state: started
    restart_policy: always
    volumes:
      - "{{ docker_data_path }}/mysql:/var/lib/mysql"
    networks:
      - name: db_network
    env:
      MYSQL_ROOT_PASSWORD: "{{ vault_mysql_root_password }}"

- include_role:
    name: copy-scripts
  vars:
    script_to_copy: backup_mysql_server

- name: set permissions for backup
  file:
    path: "{{ scripts_dir }}/backup_mysql_server"
    owner: root
    group: root
    mode: "0700"

- include_role:

    name: copy-scripts
  vars:
    script_to_copy: upload_to_s3.py

- name: add backup job for db
  cron:
    name: "backup sql db"
    special_time: daily
    job: "{{ scripts_dir }}/backup_mysql_server"

- name: deploy phpmyadmin container
  docker_container:
    name: some-phpmyadmin-container
    image: "phpmyadmin/phpmyadmin:5.0"
    state: started
    published_ports:
      - 9101:80
    restart_policy: always
    networks:
      - name: db_network
      - name: proxy_network
    env:
      PMA_HOST: some-mariadb-container
      PMA_ABSOLUTE_URI: "https://{{ local_domain_name }}/tools/phpmyadmin"
