# name: copy over nextcloud config
# template:
#   src: nextcloud/config.php.j2
#   dest: "{{ docker_data_path }}/nextcloud/config/config.php"
#   mode: "0640"
#   owner: www-data
#   group: www-data

- name: deploy nextcloud container
  become: true
  docker_container:
    name: some-nextcloud-container
    image: "nextcloud:25-apache"
    state: started
    restart_policy: always
    networks:
      - name: db_network
      - name: proxy_network
      - name: cache_network
    volumes:
      - "{{ docker_data_path }}/nextcloud:/var/www/html"
    # comment for first run setup
    env:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ vault_mysql_nextcloud_password }}"
      MYSQL_HOST: some-mariadb-container
      
      NEXTCLOUD_ADMIN_USER: "{{ vault_nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ vault_nextcloud_admin_password }}"

      REDIS_HOST: some-redis-container
      REDIS_HOST_PASSWORD: "{{ redis_password }}"

- name: copy over backup script
  include_role:
    name: copy-scripts
    apply:
      become: yes
  vars:
    script_to_copy: backup_nextcloud_db

- name: set permissions for backup
  become: yes
  file:
    path: "{{ scripts_dir }}/backup_nextcloud_db"
    owner: root
    group: root
    mode: "0700"

- name: add backup job for db
  become: yes
  cron:
    name: "backup sql db"
    special_time: daily
    job: "{{ scripts_dir }}/backup_nextcloud_db"

