# name: copy over nextcloud config
# template:
#   src: nextcloud/config.php.j2
#   dest: "{{ docker_data_path }}/nextcloud/config/config.php"
#   mode: "0640"
#   owner: www-data
#   group: www-data

- name: deploy nextcloud container
  docker_container:
    name: some-nextcloud-container
    image: "nextcloud:16-apache"
    state: started
    restart_policy: always
    networks:
      - name: db_network
      - name: proxy_network
    volumes:
      - "{{ docker_data_path }}/nextcloud:/var/www/html"
    published_ports:
      - 9100:80
    # comment for first run setup
    env:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ vault_mysql_nextcloud_password }}"
      MYSQL_HOST: some-mariadb-container
      NEXTCLOUD_ADMIN_USER: "{{ vault_nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ vault_nextcloud_admin_password }}"

- include_role:
    name: copy-scripts
  vars:
    script_to_copy: backup_nextcloud_db

- name: set permissions for backup
  file:
    path: "{{ scripts_dir }}/backup_nextcloud_db"
    owner: root
    group: root
    mode: "0700"

- include_role:
    name: copy-scripts
  vars:
    script_to_copy: upload_to_s3.py

- name: add backup job for db
  cron:
    name: "backup sql db"
    special_time: daily
    job: "{{ scripts_dir }}/backup_nextcloud_db"

