- name: make data dir
  file:
    path: "{{ docker_data_path }}/redis"
    recurse: yes
    state: directory
    owner: root
    group: root

- name: deploy redis container
  docker_container:
    name: some-redis-container
    image: "redis:latest"
    state: started
    restart: yes
    restart_policy: always
    networks:
      - name: cache_network
