---
- name: install vim
  apt: pkg={{item}}  state=installed update_cache=true
  become: true
  with_items:
    - vim
    - git
    - stow

# Configure vim with plugins and dotfiles
- name: checkout dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ user_home_directory }}/dotfiles"

- name: checkout vundle
  git:
    repo: "{{ vundle_repo }}"
    dest: '{{ user_home_directory  }}/.vim/bundle/Vundle.vim'

- name: stow vimrc file
  shell: stow -d '{{ user_home_directory }}/dotfiles' -t '{{ user_home_directory }}' '{{ item }}'
  with_items:
    - vim

- name: install vim plugins
  shell: vim -E -s -c "source ~/.vimrc" +PluginInstall +qall
  ignore_errors: true
