---
- name: generate traffic shaping script
  become: yes
  template:
    src: traffic_shaping.sh
    dest: /tmp/traffic.sh
    owner: root
    group: root
    mode: '0755'
  vars:
    s3_ranges: "{{ lookup('aws_service_ip_ranges', region='us-east1', service='S3', wantlist=True) }}"

- name: execute traffic shaping script
  become: yes
  command:
    cmd: /tmp/traffic.sh


- name: Setup cron job for turning on traffic shaping
  become: yes
  cron:
    name: "Turn on aws traffing shaping rules"
    minute: "29"
    hour: "6"
    job: "/sbin/tc class change dev {{ interface_name }} classid 1:1 cbq rate 2400kbit allot 1500 prio 5 bounded isolated"

- name: Setup cron job for turning off traffic shaping
  become: yes
  cron:
    name: "Turn off aws traffing shaping rules"
    minute: "30"
    hour: "1"
    job: "/sbin/tc class change dev {{ interface_name }} classid 1:1 cbq rate 100mbit allot 1500 prio 5 bounded isolated"
