---
- name: Install rsnapshot
  apt:
      name: rsnapshot
      state: present

- name: Copy config file
  template:
    backup: yes
    src: "rsnapshot-{{ group_names[0] }}.conf.j2"
    dest: /etc/rsnapshot.conf
    owner: root
    group: root
    validate: "echo %s; rsnapshot configtest"

- name: Copy cron config file
  template:
    backup: yes
    src: rsnapshot.j2
    dest: /etc/cron.d/rsnapshot
    owner: root
    group: root



