---
- name: Install rsnapshot
  apt:
    name: rsnapshot
    state: present

- name: Create user for pull backups
  user:
    name: rsnapshotuser
    shell: "/bin/bash"
    state: present

- name: Allow rsync access for backups
  blockinfile:
    path: /etc/sudoers
    marker: "# {mark} rsnapshotuser sudo"
    block: "rsnapshotuser ALL=(root) NOPASSWD:/usr/bin/rsync"
    validate: 'visudo -cf %s'

- name: Print warning about keys
  debug:
    msg: "Copy root's ssh pub key under the rsnapshotuser"

- name: Copy config file
  template:
    backup: yes
    src: "rsnapshot-{{ group_names[0] }}.conf.j2"
    dest: /etc/rsnapshot.conf
    owner: root
    group: root
    validate: "echo %s; rsnapshot configtest"

- name: Copy cron config file
  template:
    backup: yes
    src: rsnapshot.j2
    dest: /etc/cron.d/rsnapshot
    owner: root
    group: root
