---
- name: Create garage-door user
  user:
    name: "{{ garage_door_user }}"
    state: present

- name: Copy telegram-bot public key
  copy:
    src: "{{ telegram_user_public_key_location }}"
    dest: "{{ telegram_user_public_key_location }}"

- name: add telegram-user pub key
  authorized_key:
    user: "{{ garage_door_user }}"
    key: "{{ lookup('file', '{{ telegram_user_public_key_location }}') }}"
    state: present

# TODO: Handle checking out git repo securely
