---
- name: install apache2, rtorrent and other modules
  apt: pkg={{item}}  state=installed update_cache=true cache_valid_time=3600
  with_items:
    - apache2
    - apache2-dev
    - libapache2-mod-scgi
    - git
    - rtorrent

- name: Check if rutorrent is installed
  stat:
    path: /var/www/html/rutorrent
  register: rutorrent_directory

#TODO: Move this block to seperate file
- name: checkout rutorrent package
  git:
    repo: "{{ rutorrent_git_repo }}"
    dest: /var/www/html/rutorrent
  when: rutorrent_directory.stat.exists == False

- name: Set permissions
  file:
    path: /var/www/html/rutorrent
    owner: www-data
    group: www-data
    mode: 0755
    recurse: true
