---
- hosts: pi-server
  remote_user: deploy
  become: true
  roles:
    - { role: install-telegram-bot, tags: ['telegram'] }
    - { role: install-raspberry-pi-microservice, microservice_name: nagios_alerts, microservice_port: 25001, tags: ['services']}
    - { role: install-raspberry-pi-microservice, microservice_name: nagios_passive_check, microservice_port: 25003, garage_door_user: nagios, tags: ['services']}
    - { role: install-raspberry-pi-microservice, microservice_name: temperature_sensors, microservice_port: 25002, tags: ['services']}
