---
- import_playbook: base-book.yaml
- import_playbook: pi-server.yaml
- import_playbook: garage-door.yaml
# The remote user may need to be changed
#
# hosts: all
# become: true 
# remote_user: deploy
# remote_user: vagrant
# vars:
#   is_raspberry_pi: false # Do not add cdn mirrors for raspi
# roles:
#     - { role: remove-cdrom-and-switch-to-cdn, when: not is_raspberry_pi }
#     - install-telegram-bot
#     - base-configuration
#     - configure-environment-for-user
#     - secure-server

# hosts: garage-door-servers
# become: true
# remote_user: deploy
# remote_user: vagrant
# vars:
#     user_to_configure: "{{ garage_door_user }}"
# roles:
#     - setup-garage-door-user
#     - checkout-home-projects
