# install nrdp for remote checks
- name: Download NRDP package and extract
  unarchive:
    src: https://github.com/NagiosEnterprises/nrdp/archive/2.0.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: Create dest directory
  file:
    path: /usr/local/nrdp
    state: directory
    owner: nagios
    group: nagios

- name: Copy files into /usr/local
  shell: "cp -r clients server LICENSE* CHANGES* /usr/local/nrdp"
  args:
    chdir: /tmp/nrdp-2.0.3

# TODO: add modifications for socket path and addition of token vs copy config file
- name: copy config file
  template:
    backup: yes
    src: nrdp/config.inc.php.j2
    dest: /usr/local/nrdp/server/config.inc.php

- name: copy apache site config
  template:
    backup: yes
    src: nrdp/nrdp.conf.j2
    dest: /etc/apache2/sites-available/nrdp.conf

  register: nrdp_conf

- name: Enable apache site
  shell: "a2ensite nrdp"
  args:
    creates: /etc/apache2/sites-enabled/nrdp.conf

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
  when: nrdp_conf.changed


- name: set permissions on directory
  file:
    path: /usr/local/nrdp
    state: directory
    owner: nagios
    group: nagios
