sudo_user_to_configure: deploy
dotfiles_repo: https://github.com/avinash-oza/dotfiles.git
user_home_directory: /home/{{ user_to_configure }}
vundle_repo: https://github.com/VundleVim/Vundle.vim.git
deploy_user_public_keys:
  - apt-desktop.pub
  - id_rsa.pub
  - laptop.pub
