# name: download certbot-auto binary
# get_url:
#   url: "https://dl.eff.org/certbot-auto"
#   dest: /usr/local/bin/certbot-auto
#   owner: root
#   group: root
#   mode: "0755"
- name: Install snap for certbot
  become: true
  snap:
    name: certbot
    classic: yes

- name: install apprise
  include_role: 
    name: install-apprise

- name: setup job to auto renew if close to expiry
  cron:
    name: certbot-auto renew certificate
    special_time: weekly
    job: "/snap/bin/certbot certonly --domains {{ vault_local_domain_name }} -n --standalone --deploy-hook \"docker restart some-apache2-container\"| apprise --config /opt/scripts/apprise.conf --tag default > /dev/null 2>&1"
    state: present

