version: '2'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - "db:db"
        env_file:
            - db-variables.env
        ports:
            # Puts on 8080
            - "8080:80"
    db:
        image: mysql
        env_file:
            - db-variables.env
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql

volumes:
    db:
        driver: local
