version: '2'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - "db:db"
        env_file:
            - db-variables.env
        ports:
            # Puts on 8080
            - "8080:80"
        networks:
            - mysql_network
    db:
        image: mysql
        env_file:
            - db-variables.env
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - mysql_network

volumes:
    db:
        driver: local

networks:
    mysql_network: 
        driver: bridge
