---
- name: Register current users
  getent:
      database: passwd

- name: Delete extra users
  become: true
  user:
    name: "{{ item }}"
    state: absent
    remove: true
  with_items:
    - pi
    - avi
    - vagrant
  when: item in getent_passwd
