---
- name: Check the gpio group exists or create
  group:
    name: gpio
    state: present

- name: Create garage-door user
  user:
    name: "{{ garage_door_user }}"
    groups: gpio # to allow access to sensors
    append: yes
    state: present

- name: install prereq packages
  become: true
  apt: pkg={{item}}  state=installed update_cache=true
  with_items:
    - git
#   - virtualenv
    - python-pip
    - python-virtualenv
    - python-dev

- name: Create virtual env with bottle
  pip:
    name: "{{ item }}"
    virtualenv_python: python2.7
    virtualenv: "/home/{{ garage_door_user }}/virtual-env"
  with_items:
    - bottle
    - Rpi.GPIO

- name: Checkout garage-door-server
  git:
    repo: https://github.com/avinash-oza/raspberry-pi-microservices.git
    dest: /home/{{ garage_door_user }}/raspberry-pi-microservices
    force: yes

- name: Copy config and create config
  template:
    src: garage-door.config
    dest: "/home/{{ garage_door_user }}/raspberry-pi-microservices/garage_door/garage-door.config"
    owner: "{{ garage_door_user }}"
    group: "{{ garage_door_user }}"
    mode: 0755

- name: Change ownership of all files to user
  file:
    path: "/home/{{ garage_door_user }}"
    owner: "{{ garage_door_user }}"
    group: "{{ garage_door_user }}"
    state: directory
    recurse: yes

- name: Copy systemd file for starting service on boot
  become: yes
  template:
    src: garage-door.service
    dest: /etc/systemd/system
    mode: 0644

- name: Enable service to run on boot and start
  become: yes
  service:
    name: garage-door
    state: restarted
    enabled: true
