# ADD ABILITY TO CLONE LATEST DUMPS
---
- name: install phpmyadmin, mysql-server and apache
  apt: pkg={{item}}  state=installed update_cache=true
  become: true
  with_items:
    - apache2
    - mysql-server
    - python-mysqldb
    - phpmyadmin

- name: Start mysql server
  service:
      name: mysql
      state: started
      enabled: true

- name: Update mysql root password
  become: true
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

- name: include phpmyadmin config into apache
  notify: restart apache2
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    regexp: "^Include.+phpmyadmin.+$"
    line: "Include /etc/phpmyadmin/apache.conf"
    insertafter: "EOF"
    backup: true

- name: Copy git private key for checkout
  copy:
    src: "{{ mysql_backups_git_private_key_path }}"
    dest: /tmp/git.key
    mode: 0600

- name: Checkout mysql backups
  git:
    repo: "git@git-server:mysql-backup.git"
    key_file: /tmp/git.key
    dest: /tmp/mysql-backup
    accept_hostkey: yes

- name: Restore mysql tables from backup
  mysql_db:
    name: "{{ item }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: import
    target: "/tmp/mysql-backup/{{ item }}.sql"
  with_items:
    - temperature
    - telegram_bot
    - asterisk
    - asteriskcdrdb

- name: Create telegram and temperature user and grant access
  mysql_user: 
    host: "%"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item }}"
    password: "{{ lookup('password', 'credentials/mysql/' +  item  + '.txt length=15') }}"
    priv: "{{ item }}.*:ALL,GRANT"
    state: present
  with_items:
    - temperature
    - telegram_bot

- name: Create read only user for backups
  mysql_user: 
    host: "%"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "BACKUP"
    password: "backup"
    priv: "*.*:LOCK TABLES,SELECT,USAGE"
    state: present
