---
- name: install nagios3 and plugins
  apt: pkg={{item}}  state=installed update_cache=false
  with_items:
    - nagios3
    - nagios-plugins-contrib
    - nagios-nrpe-plugin

- name: Enable nagios external commands
  lineinfile:
    backup: true
    dest: /etc/nagios3/nagios.cfg
    state: present
    regexp: '^check_external_commands'
    line: "check_external_commands=1"

- name: Disable logging of passive checks
  lineinfile:
    backup: true
    dest: /etc/nagios3/nagios.cfg
    state: present
    regexp: '^log_passive_checks'
    line: "log_passive_checks=0"

- name: Change cgi-bin path
  lineinfile:
    backup: true
    dest: /etc/nagios3/cgi.cfg
    state: present
    regexp: '^url_html_path'
    line: "url_html_path=/tools/nagios3"

- name: Update web config to proper path
  lineinfile:
    backup: true
    dest: /usr/share/nagios3/htdocs/config.inc.php
    state: present
    regexp: "^\\$cfg\\['cgi_base_url'\\]"
    line: "$cfg['cgi_base_url']='/tools/cgi-bin/nagios3';"

- name: Add users to the nagios group
  user:
    name: "{{ item }}"
    groups: nagios # for passive checks
    append: yes
    state: present
  with_items:
    - nagios
    - www-data

- name: Symlink airvpn_checker plugin with nagios plugins
  file:
    src: "{{ user_home_directory }}/home-projects/pi/airvpn_checker"
    dest: /usr/lib/nagios/plugins/check_airvpn_status
    state: link
    owner: root
    group: root

- name: copy airvpn config
  template:
    src: airvpn_checker.config.j2
    dest: "{{ user_home_directory }}/home-projects/pi/airvpn_checker/airvpn.config"
    owner: "nagios"
    group: "nagios"


# TODO: ################## checkout check_sip, update perl version to lib, install libswitch-perl


###################
# TODO: ADD COPY OF SCRIPT to /opt/nagios

- name: copy over nagios commands.cfg
  tags: config
  template:
    backup: true
    src: "commands.cfg"
    dest: "/etc/nagios3/commands.cfg"

- name: copy over nagios configs
  tags: config
  template:
    backup: true
    src: "{{ item }}"
    dest: "/etc/nagios3/conf.d/{{ item | basename | regex_replace('\\.j2', '') }}"
  with_fileglob:
    - ../templates/conf.d/*

- name: copy over web config
  tags: config
  template:
    backup: true
    src: nagios3.conf.j2
    dest: /etc/apache2/conf-available/nagios3.conf

- name: Allow nagios user sudo access for plugins
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^nagios'
    line: "nagios ALL=(ALL) NOPASSWD:/usr/lib/nagios/plugins/,{{ user_home_directory }}/home-projects/pi"
    validate: 'visudo -cf %s'

- name: Restart nagios server
  service:
    name: nagios3
    state: restarted

- name: Generate ssh key for nagios user
  user:
    name: nagios
    generate_ssh_key: yes
    ssh_key_comment: "nagios@{{ ansible_hostname }}"

- name: Fetch public key to local machine
  fetch:
    src: "{{ user_home_directory}}/.ssh/id_rsa.pub"
    dest: "{{ playbook_dir }}/nagios_pub_key.pub"
    fail_on_missing: yes
    flat: yes

#TODO: handle copying over apache configs

# install nrdp for remote checks
- name: Download NRDP package and extract
  unarchive:
    src: https://github.com/NagiosEnterprises/nrdp/releases/download/1.5.2/1.5.2.tar.gz
    dest: /tmp
    remote_src: yes

- name: Create dest directory
  file:
    path: /usr/local/nrdp
    state: directory
    owner: nagios
    group: nagios

- name: Copy files into /usr/local
  shell: "cp -r clients server LICENSE* CHANGES* /usr/local/nrdp"
  args:
    chdir: /tmp/nrdp-1.5.2

- name: copy config file
  template:
    backup: yes
    src: config.inc.php.j2
    dest: /usr/local/nrdp/server/config.inc.php

- name: copy apache site config
  template:
    backup: yes
    src: nrdp.conf.j2
    dest: /etc/apache2/sites-available/nrdp.conf

  register: nrdp_conf

- name: Enable apache site
  shell: "a2ensite nrdp"
  args:
    creates: /etc/apache2/sites-enabled/nrdp.conf

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
  when: nrdp_conf.changed


- name: set permissions on directory
  file:
    path: /usr/local/nrdp
    state: directory
    owner: nagios
    group: nagios
