---
- name: Remove cdrom
  apt_repository:
    repo: "deb cdrom:[Debian GNU/Linux 8.7.1 _Jessie_ - Official amd64 CD Binary-1 20170116-11:01]/ jessie main"
    state: absent
- name: Remove http mirrors
  apt_repository:
    repo: "deb http://ftp.us.debian.org/debian/ jessie main"
    state: absent
- name: Remove http mirrors source
  apt_repository:
    repo: "deb-src http://ftp.us.debian.org/debian/ jessie main"
    state: absent
- name: add httpredir mirrors
  apt_repository:
    repo: "deb http://httpredir.debian.org/debian/ jessie main"
    state: present
- name: add http mirrors source
  apt_repository:
    repo: "deb-src http://httpredir.debian.org/debian/ jessie main"
    state: present
    update_cache: yes
    # only add on the last one

# configure sudo for other operations
- name: install sudo
  apt: pkg=sudo  state=installed update_cache=true

- name: Check for wheel group
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: add to wheel group
  user: name=avi groups=wheel append=yes state=present createhome=no

