# noqa: var-naming[no-role-prefix]
airvpn_api_key: "{{ vault_airvpn_api_key }}"

nagios_command_group: nagcmd
nagios_command_file_path: "/var/lib/nagios4/rw/nagios.cmd"
nagios_results_file_path: "/var/lib/nagios4/spool/checkresults"

nagios_contact_name: "{{ vault_nagios_contact_name }}"
nagios_contact_alias: "{{ vault_nagios_contact_alias }}"
nagios_contact_email: "{{ vault_nagios_contact_email }}"

# Host and IP address definitions for various servers and services
apt_server_host_name: apt-server
apt_server_ip_address: 192.168.0.187

localhost_host_name: localhost
localhost_ip_address: 127.0.0.1

main_node_host_name: main-node
main_node_ip_address: 192.168.0.70

main_server_host_name: main-server
main_server_ip_address: 172.16.1.10

pi_hole_2_host_name: pi-hole-2
pi_hole_2_ip_address: 192.168.0.120

pi_hole_3_host_name: pi-hole-3
pi_hole_3_ip_address: 192.168.0.193

proxmox_host_name: proxmox
proxmox_ip_address: 192.168.0.74
