
- name: deploy caddy container
  community.docker.docker_container:
    name: some-caddy-container
    image: "lucaslorentz/caddy-docker-proxy:ci-alpine"
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_data_path }}/caddy:/data"
    networks:
      - name: proxy_network
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    env:
      CADDY_INGRESS_NETWORKS: "proxy_network"
