---
# This assumes that anaconda already exists in /opt/anaconda

- name: install git
  apt:
    name: git
    state: present
    update_cache: false

- name: Create telegram user
  user:
    name: "{{ telegram_user_account }}"
    state: present

- name: checkout telegram-bot
  git:
    repo: "{{ telegram_bot_repo }}"
    dest: "{{ telegram_checkout_location }}"
    accept_hostkey: yes
    force: yes

- name: check for telegram-bot conda env
  shell: "{{ telegram_anaconda_path }}/conda env list | grep telegram-bot | cat"
  register: conda_env_exists

- name: Create conda env
  shell: "{{ telegram_anaconda_path }}/conda create -n telegram-bot python=3"
  when: conda_env_exists.stdout == ""

- name: Install package and deps
  shell: "source {{ telegram_anaconda_path }}/activate telegram-bot && {{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ telegram_checkout_location }}"
  with_items:
    - "pip install -r requirements.txt"
    - "pip install ."

- name: Create telegram-bot start file
  template:
    src: start_telegram_bot.sh
    dest: "{{ telegram_checkout_location }}/start_telegram_bot.sh"
    owner: "{{ telegram_user_account }}"
    group: "{{ telegram_user_account }}"
    mode: 0755

- name: "Create config file location"
  become: yes
  file:
    path: "/etc/telegram-bot/"
    state: directory
    owner: "{{ telegram_user_account }}"
    group: "{{ telegram_user_account }}"
    mode: 0755
  
- name: Create telegram-bot config file
  template:
    src: bot.config
    dest: "/etc/telegram-bot/bot.config"
    owner: "{{ telegram_user_account }}"
    group: "{{ telegram_user_account }}"
    mode: 0744

- name: Configure rotation of logfile
  template:
    src: telegram_log_rotate
    dest: "/etc/logrotate.d/telegram_log_rotate"

- name: "Create logfile location {{ telegram_log_location }}"
  become: yes
  file:
    path: "{{ telegram_log_location }}"
    state: directory
    owner: "{{ telegram_user_account }}"
    group: "{{ telegram_user_account }}"
    mode: 0755
  
- name: Copy systemd file for starting telegram-bot on boot
  become: yes
  template:
    src: telegram-bot.service
    dest: /etc/systemd/system
    mode: 0644

- name: Enable telegram-bot to run on boot and start
  become: yes
  service:
    name: telegram-bot.service
    state: restarted
    enabled: true
