---
# configure sudo for other operations
- name: install sudo
  apt: pkg=sudo  state=installed update_cache=true

- name: Check for sudo group
  group:
    name: sudo
    state: present

- name: Allow sudo group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create deployment/sudo user
  user:
    name: "{{ sudo_user_to_configure }}" 
    password: "{{ sudo_user_password | password_hash('sha512') }}"
    shell: /bin/bash

- name: add to sudo group
  user: name="{{ sudo_user_to_configure }}" groups=sudo append=yes state=present createhome=no

