---
- name: install virtualenv and other requirements
  apt: pkg={{item}}  state=installed update_cache=false
  with_items:
    - git
#   - virtualenv
    - python-pip
    - python-virtualenv
    - python3-pip

- name: Create telegram user
  user:
    name: "{{ telegram_user_account }}"
    state: present

# Configure vim with plugins and dotfiles
- name: checkout telegram-bot
# become: yes
# become_user: "{{ telegram_user_account }}"
  git:
    repo: "{{ telegram_bot_repo }}"
    dest: "{{ telegram_checkout_location }}"
    accept_hostkey: yes
    force: yes # Wipes changes but makes the book succeed

- name: install telegram-bot virtualenv
# become: yes
# become_user: "{{ telegram_user_account }}"
  pip:
    requirements: "{{ telegram_checkout_location }}/requirements.txt"
    virtualenv_python: python2.7
    virtualenv: "{{ telegram_bot_virtual_env_location }}"

- name: Create telegram-bot start file
# become: yes
# become_user: "{{ telegram_user_account }}"
  template:
    src: start_telegram_bot.sh
    dest: "{{ telegram_checkout_location }}/start_telegram_bot.sh"
    owner: "{{ telegram_user_account }}"
    group: "{{ telegram_user_account }}"
    mode: 0755

- name: Convert ownership of all files in home directory to user
  file:
    path: "/home/{{ telegram_user_account }}"
    owner: "{{ telegram_user_account }}"
    group: "{{ telegram_user_account }}"
    state: directory
    recurse: yes

  
# name: Copy systemd file for starting telegram-bot on boot
# become: yes
# template:
#   src: telegram-bot.service
#   dest: /etc/systemd/system
#   mode: 0644

# name: Enable telegram-bot to run on boot and start
# become: yes
# service:
#   name: telegram-bot
#   state: started
#   enabled: true
