---
# noqa: syntax-check[unknown-module]
# configure sudo for other operations
- name: Check for sudo group
  ansible.builtin.group:
    name: sudo
    state: present
  when: allow_sudo | bool

- name: Allow sudo group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: allow_sudo | bool

- name: create configured user and add to sudo group
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user_shell }}"
    groups: "{{ 'sudo' if (allow_sudo | bool) else omit }}"
    append: "{{ true if (allow_sudo | bool) else omit }}"
    state: present

- name: Add authorized keys for SSH configured user
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ item }}"
  with_file: "{{ add_public_keys }}"

- name: remove old keys
  authorized_key:
    user: "{{ user_name }}"
    state: absent
    key: "{{ item }}"
  with_file: "{{ remove_public_keys }}"

# name: setup_dotfiles
# include_role:
#   name: setup_dotfiles
# vars:
#   user_name: "{{ user_name }}"

# name: setup vim
# include_role:
#   name: install_and_configure_vim_for_user
# vars:
#   user_name: "{{ user_name }}"
