---
- name: Register current users
  getent:
      database: passwd

- name: Scramble extra user passwords
  user:
    name: "{{ item }}"
    password: "{{ lookup('password', 'credentials/{{ item }}/password.txt length=20') | password_hash('sha512') }}"
  with_items:
    - pi
    - avi
    - vagrant
  when: item in getent_passwd
