---
- name: install prereq packages
  become: true
  apt:
    pkg: ['python-pip','python-virtualenv', 'python-dev']
    state: present

- name: create scripts directory
  file:
    state: directory
    path: /opt/scripts
    owner: root
    group: root

- name: copy over script for temperature publishing
  template:
    src: report_temperatures.py
    dest: /opt/scripts
    owner: root
    group: root

- name: Install report temps cron job
  cron:
    name: report_temps_cron_job
    minute: "*/10"
    job: "AWS_DEFAULT_REGION={{ vault_aws_default_region}} AWS_ACCESS_KEY_ID={{ vault_aws_access_key_id }} AWS_SECRET_ACCESS_KEY={{ vault_aws_secret_access_key }} {{ python_virtual_env }}/bin/python /opt/scripts/report_temperatures.py"
    state: present
    user: root

- name: Create virtual env for temperatures
  pip:
    virtualenv_python: python3
    virtualenv: "{{ python_virtual_env }}"
    state: present
    name: [ 'boto3', 'requests' ]
