#!/usr/bin/bash -e

tar czf /tmp/mediawiki_images.tgz -C {{ docker_data_path }}/mediawiki/images .

rclone --config {{ scripts_dir }}/rclone.conf copy /tmp/mediawiki_images.tgz {{ vault_rclone_remote_name }}:/mediawiki/

# upload db backup

/usr/bin/docker exec some-mariadb-container mysqldump --single-transaction -u root -p{{ vault_mysql_root_password }} mediawiki | gzip -9 > /tmp/mediawiki_backup.gz

rclone --config {{ scripts_dir }}/rclone.conf copy /tmp/mediawiki_backup.gz {{ vault_rclone_remote_name }}:/db/

rm /tmp/mediawiki_backup.gz
rm /tmp/mediawiki_images.tgz
