#!/usr/bin/bash -e

tar czf /tmp/bookstack_images.tgz -C {{ docker_data_path }}/bookstack/ .

rclone --config {{ scripts_dir }}/rclone.conf copy /tmp/bookstack_images.tgz {{ vault_rclone_remote_name }}:/bookstack/

rm /tmp/bookstack_images.tgz
