#!/usr/bin/bash -e

tar czf /tmp/bookstack_images.tgz -C {{ docker_data_path }}/bookstack/ .

AWS_DEFAULT_REGION={{ vault_aws_default_region }} AWS_ACCESS_KEY_ID={{ vault_aws_keys.bookstack.key_id }} AWS_SECRET_ACCESS_KEY={{ vault_aws_keys.bookstack.access_key }} \
 {{ python_root }}/{{ python_bin }} {{ scripts_dir }}/upload_to_s3.py \
  --upload-file /tmp/bookstack_images.tgz \
  --bucket-name {{ vault_aws_projects_bucket }} \
  --dest-key backups/bookstack/bookstack_images.tgz

# upload db backup

/usr/bin/docker exec some-mariadb-container mysqldump --single-transaction -u root -p{{ vault_mysql_root_password }} bookstack | gzip -9 > /tmp/bookstack_backup.gz

AWS_DEFAULT_REGION={{ vault_aws_default_region }} AWS_ACCESS_KEY_ID={{ vault_aws_keys.bookstack.key_id }} AWS_SECRET_ACCESS_KEY={{ vault_aws_keys.bookstack.access_key }} \
 {{ python_root }}/{{ python_bin }} {{ scripts_dir }}/upload_to_s3.py \
  --upload-file /tmp/bookstack_backup.gz \
  --bucket-name {{ vault_aws_projects_bucket }} \
  --dest-key backups/db/bookstack_backup.gz

rm /tmp/bookstack_backup.gz
rm /tmp/bookstack_images.tgz
