---
- name: install mysql-server
  apt: pkg={{item}}  state=installed update_cache=true
  become: true
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start mysql server
  service:
      name: mysql
      state: started
      enabled: true

- name: Update mysql root password
  sudo: yes
  mysql_user:
      name: root
      host: "{{ item }}"
      password: apple
      login_user: root
      login_password: apple
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

# Restore dataase and users
- name: Copy dump 
  copy: 
    src: "{{ mysql_dump_file }}"
    dest: /tmp

- name: Restore dump
  mysql_db:
    login_user: root
    login_password: apple
    state: import
    name: all
    target: /tmp/{{ mysql_dump_file }}
